"""initial

Revision ID: a4229c25081e
Revises: 
Create Date: 2026-01-26 18:02:22.825208

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import table, column
from passlib.context import CryptContext

pwd_context = CryptContext(schemes=["bcrypt"], deprecated="auto")

def get_password_hash(password: str) -> str:
    return pwd_context.hash(password)


# revision identifiers, used by Alembic.
revision = 'a4229c25081e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('account_balances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_name', sa.String(), nullable=False),
    sa.Column('balance', sa.Numeric(precision=30, scale=10), nullable=False),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_account_balances_account_name'), 'account_balances', ['account_name'], unique=False)
    op.create_index(op.f('ix_account_balances_id'), 'account_balances', ['id'], unique=False)
    op.create_table('agents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('commission_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agents_id'), 'agents', ['id'], unique=False)
    op.create_index(op.f('ix_agents_name'), 'agents', ['name'], unique=False)
    op.create_table('clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('contact_info', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clients_id'), 'clients', ['id'], unique=False)
    op.create_index(op.f('ix_clients_name'), 'clients', ['name'], unique=False)
    op.create_table('currencies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('is_crypto', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_currencies_code'), 'currencies', ['code'], unique=True)
    op.create_index(op.f('ix_currencies_id'), 'currencies', ['id'], unique=False)
    op.create_table('deal_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('client_sends_currency', sa.String(), nullable=True),
    sa.Column('client_receives_currency', sa.String(), nullable=True),
    sa.Column('routes_config', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deal_templates_id'), 'deal_templates', ['id'], unique=False)
    op.create_table('internal_companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('contact_info', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_internal_companies_id'), 'internal_companies', ['id'], unique=False)
    op.create_index(op.f('ix_internal_companies_name'), 'internal_companies', ['name'], unique=False)
    op.create_table('route_commissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('route_type', sa.String(), nullable=False),
    sa.Column('commission_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('commission_fixed', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('is_fixed_currency', sa.Boolean(), nullable=False),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_route_commissions_id'), 'route_commissions', ['id'], unique=False)
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('contact_info', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companies_id'), 'companies', ['id'], unique=False)
    op.create_index(op.f('ix_companies_name'), 'companies', ['name'], unique=False)
    op.create_table('deals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('manager_id', sa.Integer(), nullable=False),
    sa.Column('total_eur_request', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('client_rate_percent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('client_sends_currency', sa.String(), nullable=True),
    sa.Column('client_receives_currency', sa.String(), nullable=True),
    sa.Column('deal_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('total_usdt_calculated', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('effective_rate', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('total_cost_usdt', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('gross_margin_usdt', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('net_profit_usdt', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('partner_share_usdt', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('director_comment', sa.Text(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('senior_manager_id', sa.Integer(), nullable=True),
    sa.Column('senior_manager_comment', sa.Text(), nullable=True),
    sa.Column('approved_by_senior_manager_at', sa.DateTime(), nullable=True),
    sa.Column('client_debt_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('client_paid_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('is_client_debt', sa.Boolean(), nullable=False),
    sa.Column('client_payment_confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['manager_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['senior_manager_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deals_id'), 'deals', ['id'], unique=False)
    op.create_table('internal_company_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('account_name', sa.String(), nullable=False),
    sa.Column('account_number', sa.String(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('balance', sa.Numeric(precision=30, scale=10), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['internal_companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_internal_company_accounts_id'), 'internal_company_accounts', ['id'], unique=False)
    op.create_table('company_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('account_name', sa.String(), nullable=False),
    sa.Column('account_number', sa.String(), nullable=False),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_accounts_id'), 'company_accounts', ['id'], unique=False)
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deal_id', sa.Integer(), nullable=False),
    sa.Column('from_currency', sa.String(), nullable=True),
    sa.Column('to_currency', sa.String(), nullable=True),
    sa.Column('exchange_rate', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('client_company_id', sa.Integer(), nullable=True),
    sa.Column('amount_for_client', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('route_type', sa.String(), nullable=True),
    sa.Column('internal_company_id', sa.Integer(), nullable=True),
    sa.Column('internal_company_account_id', sa.Integer(), nullable=True),
    sa.Column('amount_from_account', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('bank_commission_id', sa.Integer(), nullable=True),
    sa.Column('crypto_account_id', sa.Integer(), nullable=True),
    sa.Column('exchange_from_currency', sa.String(), nullable=True),
    sa.Column('exchange_to_currency', sa.String(), nullable=True),
    sa.Column('crypto_exchange_rate', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('agent_commission_id', sa.Integer(), nullable=True),
    sa.Column('exchange_commission_id', sa.Integer(), nullable=True),
    sa.Column('exchange_bank_commission_id', sa.Integer(), nullable=True),
    sa.Column('partner_company_id', sa.Integer(), nullable=True),
    sa.Column('amount_to_partner_usdt', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('amount_partner_sends', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('partner_commission_id', sa.Integer(), nullable=True),
    sa.Column('partner_50_50_company_id', sa.Integer(), nullable=True),
    sa.Column('amount_to_partner_50_50_usdt', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('amount_partner_50_50_sends', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('partner_50_50_commission_id', sa.Integer(), nullable=True),
    sa.Column('calculated_route_income', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('calculated_commission_total', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('cost_usdt', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('client_price_usdt', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('profit_usdt', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('partner_profit_usdt', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('final_income', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'PAID', 'ERROR', name='transactionstatus'), nullable=True),
    sa.Column('payment_proof_file', sa.String(), nullable=True),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['agent_commission_id'], ['route_commissions.id'], ),
    sa.ForeignKeyConstraint(['bank_commission_id'], ['route_commissions.id'], ),
    sa.ForeignKeyConstraint(['client_company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['crypto_account_id'], ['account_balances.id'], ),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], ),
    sa.ForeignKeyConstraint(['exchange_bank_commission_id'], ['route_commissions.id'], ),
    sa.ForeignKeyConstraint(['exchange_commission_id'], ['route_commissions.id'], ),
    sa.ForeignKeyConstraint(['internal_company_account_id'], ['internal_company_accounts.id'], ),
    sa.ForeignKeyConstraint(['internal_company_id'], ['internal_companies.id'], ),
    sa.ForeignKeyConstraint(['partner_50_50_commission_id'], ['route_commissions.id'], ),
    sa.ForeignKeyConstraint(['partner_50_50_company_id'], ['internal_companies.id'], ),
    sa.ForeignKeyConstraint(['partner_commission_id'], ['route_commissions.id'], ),
    sa.ForeignKeyConstraint(['partner_company_id'], ['internal_companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_id'), 'transactions', ['id'], unique=False)
    op.create_table('account_balance_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_balance_id', sa.Integer(), nullable=False),
    sa.Column('previous_balance', sa.Numeric(precision=30, scale=10), nullable=False),
    sa.Column('new_balance', sa.Numeric(precision=30, scale=10), nullable=False),
    sa.Column('change_amount', sa.Numeric(precision=30, scale=10), nullable=False),
    sa.Column('change_type', sa.Enum('AUTO', 'MANUAL', name='balancechangetype'), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=True),
    sa.Column('deal_id', sa.Integer(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('changed_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['account_balance_id'], ['account_balances.id'], ),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_account_balance_history_id'), 'account_balance_history', ['id'], unique=False)
    # ### end Alembic commands ###
    
    # ========== SEED DATA ==========
    
    # Users
    users = table('users',
        column('id', sa.Integer),
        column('email', sa.String),
        column('hashed_password', sa.String),
        column('full_name', sa.String),
        column('role', sa.String),
        column('is_active', sa.String),
    )
    op.bulk_insert(users, [
        {'email': 'manager@test.com', 'hashed_password': get_password_hash('manager123'), 'full_name': 'Manager Test', 'role': 'manager', 'is_active': 'true'},
        {'email': 'accountant@test.com', 'hashed_password': get_password_hash('accountant123'), 'full_name': 'Accountant Test', 'role': 'accountant', 'is_active': 'true'},
        {'email': 'director@test.com', 'hashed_password': get_password_hash('director123'), 'full_name': 'Director Test', 'role': 'director', 'is_active': 'true'},
        {'email': 'senior@test.com', 'hashed_password': get_password_hash('senior123'), 'full_name': 'Senior Manager Test', 'role': 'senior_manager', 'is_active': 'true'},
    ])
    
    # Currencies
    currencies = table('currencies',
        column('code', sa.String),
        column('name', sa.String),
        column('is_crypto', sa.Boolean),
        column('is_active', sa.Boolean),
    )
    op.bulk_insert(currencies, [
        {'code': 'EUR', 'name': 'Euro', 'is_crypto': False, 'is_active': True},
        {'code': 'USD', 'name': 'US Dollar', 'is_crypto': False, 'is_active': True},
        {'code': 'GBP', 'name': 'British Pound', 'is_crypto': False, 'is_active': True},
        {'code': 'CHF', 'name': 'Swiss Franc', 'is_crypto': False, 'is_active': True},
        {'code': 'USDT', 'name': 'Tether', 'is_crypto': True, 'is_active': True},
        {'code': 'USDC', 'name': 'USD Coin', 'is_crypto': True, 'is_active': True},
        {'code': 'BTC', 'name': 'Bitcoin', 'is_crypto': True, 'is_active': True},
        {'code': 'ETH', 'name': 'Ethereum', 'is_crypto': True, 'is_active': True},
    ])
    
    # Internal Companies
    internal_companies = table('internal_companies',
        column('id', sa.Integer),
        column('name', sa.String),
        column('contact_info', sa.String),
        column('notes', sa.Text),
    )
    op.bulk_insert(internal_companies, [
        {'id': 1, 'name': 'Company A', 'contact_info': 'company_a@example.com', 'notes': 'Main company'},
        {'id': 2, 'name': 'Company B', 'contact_info': 'company_b@example.com', 'notes': 'Backup company'},
        {'id': 3, 'name': 'Partner 1', 'contact_info': 'partner1@example.com', 'notes': 'Supply partner'},
        {'id': 4, 'name': 'Partner 2', 'contact_info': 'partner2@example.com', 'notes': 'Split 50/50 partner'},
    ])
    
    # Internal Company Accounts
    internal_accounts = table('internal_company_accounts',
        column('company_id', sa.Integer),
        column('account_name', sa.String),
        column('account_number', sa.String),
        column('currency', sa.String),
        column('balance', sa.Numeric),
        column('is_active', sa.Boolean),
    )
    op.bulk_insert(internal_accounts, [
        {'company_id': 1, 'account_name': 'EUR Account A', 'account_number': 'DE89370400440532013000', 'currency': 'EUR', 'balance': 100000, 'is_active': True},
        {'company_id': 1, 'account_name': 'USD Account A', 'account_number': 'DE89370400440532013001', 'currency': 'USD', 'balance': 50000, 'is_active': True},
        {'company_id': 2, 'account_name': 'EUR Account B', 'account_number': 'DE89370400440532013002', 'currency': 'EUR', 'balance': 75000, 'is_active': True},
        {'company_id': 2, 'account_name': 'GBP Account B', 'account_number': 'GB29NWBK60161331926819', 'currency': 'GBP', 'balance': 30000, 'is_active': True},
    ])
    
    # Account Balances (crypto)
    account_balances = table('account_balances',
        column('account_name', sa.String),
        column('currency', sa.String),
        column('balance', sa.Numeric),
        column('notes', sa.Text),
    )
    op.bulk_insert(account_balances, [
        {'account_name': 'Binance USDT', 'currency': 'USDT', 'balance': 500000, 'notes': 'Main crypto account'},
        {'account_name': 'Binance USDC', 'currency': 'USDC', 'balance': 200000, 'notes': 'Backup account'},
        {'account_name': 'Kraken BTC', 'currency': 'BTC', 'balance': 10, 'notes': 'Bitcoin cold wallet'},
        {'account_name': 'Kraken ETH', 'currency': 'ETH', 'balance': 50, 'notes': 'Ethereum'},
    ])
    
    # Clients
    clients = table('clients',
        column('id', sa.Integer),
        column('name', sa.String),
        column('contact_info', sa.String),
        column('notes', sa.String),
        column('is_active', sa.Boolean),
    )
    op.bulk_insert(clients, [
        {'id': 1, 'name': 'Client A', 'contact_info': 'client_a@example.com', 'notes': 'VIP client', 'is_active': True},
        {'id': 2, 'name': 'Client B', 'contact_info': 'client_b@example.com', 'notes': 'Standard client', 'is_active': True},
        {'id': 3, 'name': 'Client C', 'contact_info': 'client_c@example.com', 'notes': 'New client', 'is_active': True},
    ])
    
    # Companies (client companies)
    companies = table('companies',
        column('client_id', sa.Integer),
        column('name', sa.String),
        column('contact_info', sa.String),
        column('notes', sa.Text),
    )
    op.bulk_insert(companies, [
        {'client_id': 1, 'name': 'Alpha LLC', 'contact_info': 'alpha@client.com', 'notes': 'Main company'},
        {'client_id': 1, 'name': 'Alpha Inc', 'contact_info': 'alpha_inc@client.com', 'notes': 'Secondary'},
        {'client_id': 2, 'name': 'Beta Corp', 'contact_info': 'beta@client.com', 'notes': 'Main company'},
        {'client_id': 3, 'name': 'Gamma Ltd', 'contact_info': 'gamma@client.com', 'notes': 'Main company'},
    ])
    
    # Company Accounts
    company_accounts = table('company_accounts',
        column('company_id', sa.Integer),
        column('account_name', sa.String),
        column('account_number', sa.String),
        column('currency', sa.String),
        column('is_active', sa.Boolean),
    )
    op.bulk_insert(company_accounts, [
        {'company_id': 1, 'account_name': 'Main EUR', 'account_number': 'BY20ALFA30120000000000000000', 'currency': 'EUR', 'is_active': True},
        {'company_id': 1, 'account_name': 'USD Account', 'account_number': 'BY20ALFA30120000000000000001', 'currency': 'USD', 'is_active': True},
        {'company_id': 2, 'account_name': 'Main', 'account_number': 'BY20BETA30120000000000000000', 'currency': 'EUR', 'is_active': True},
        {'company_id': 3, 'account_name': 'Settlement', 'account_number': 'BY20GAMM30120000000000000000', 'currency': 'EUR', 'is_active': True},
        {'company_id': 4, 'account_name': 'Main', 'account_number': 'BY20DELT30120000000000000000', 'currency': 'EUR', 'is_active': True},
    ])


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_account_balance_history_id'), table_name='account_balance_history')
    op.drop_table('account_balance_history')
    op.drop_index(op.f('ix_transactions_id'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_company_accounts_id'), table_name='company_accounts')
    op.drop_table('company_accounts')
    op.drop_index(op.f('ix_internal_company_accounts_id'), table_name='internal_company_accounts')
    op.drop_table('internal_company_accounts')
    op.drop_index(op.f('ix_deals_id'), table_name='deals')
    op.drop_table('deals')
    op.drop_index(op.f('ix_companies_name'), table_name='companies')
    op.drop_index(op.f('ix_companies_id'), table_name='companies')
    op.drop_table('companies')
    op.drop_index(op.f('ix_route_commissions_id'), table_name='route_commissions')
    op.drop_table('route_commissions')
    op.drop_index(op.f('ix_internal_companies_name'), table_name='internal_companies')
    op.drop_index(op.f('ix_internal_companies_id'), table_name='internal_companies')
    op.drop_table('internal_companies')
    op.drop_index(op.f('ix_deal_templates_id'), table_name='deal_templates')
    op.drop_table('deal_templates')
    op.drop_index(op.f('ix_currencies_id'), table_name='currencies')
    op.drop_index(op.f('ix_currencies_code'), table_name='currencies')
    op.drop_table('currencies')
    op.drop_index(op.f('ix_clients_name'), table_name='clients')
    op.drop_index(op.f('ix_clients_id'), table_name='clients')
    op.drop_table('clients')
    op.drop_index(op.f('ix_agents_name'), table_name='agents')
    op.drop_index(op.f('ix_agents_id'), table_name='agents')
    op.drop_table('agents')
    op.drop_index(op.f('ix_account_balances_id'), table_name='account_balances')
    op.drop_index(op.f('ix_account_balances_account_name'), table_name='account_balances')
    op.drop_table('account_balances')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###

